language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install tensorflow
  - pip install numpy
  - pip install pytest
# command to run tests
script:
  - python -m pytest tests
